"""
DO NOT EDIT THIS FILE 

Run these tests `python binarysearch_test.py` on the command line to 
test the correctness of your binarysearch.py functions

"""

import unittest

# change to binarysearch
from binarysearch_sample import basic_binary_search

class BinarySearchTest(unittest.TestCase):

	def test_first_value(self):
		self.assertEqual(0, basic_binary_search([5,6,7,10,12,15,19,20], 5))

	def test_last_value(self):
		self.assertEqual(7, basic_binary_search([5,6,7,10,12,15,19,20], 20))

	def test_middle_value(self):
		self.assertEqual(4, basic_binary_search([5,6,7,10,12,19,20], 12))

	def test_negatives(self):
		self.assertEqual(1, basic_binary_search([-201,-19,-10,-5,-2,-1], -19))




if __name__ == '__main__':
	unittest.main() 

